name: SydhavnsCompagniet
favicon: null
layout_spectrum: 0.97652
typography_spectrum: 0.00807
title: SydhavnsCompagniet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c71c22'
    - '#5f9e45'
    - '#9dc08b'
    - '#c66264'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
